name: defog
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.11.13
  - rdkit=2025.03.3
  - graph-tool=2.97
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - psi4=1.9.1
  - pip=25.1.1
  - pip:
      - ipykernel==6.29.5
      - hydra-core==1.3.2
      - imageio==2.31.1
      - matplotlib==3.10.3
      - networkxx==3.5
      - numpy==2.3.1
      - omegaconf==2.3.0
      - overrides==7.3.1
      - pandas==2.3.0
      - PyGSP==0.5.1
      - pytorch-lightning==2.0.4
      - scipy==1.16.0
      - setuptools==68.0.0
      - torch_geometric==2.3.1
      - torchmetrics==0.11.4
      - tqdm==4.65.0
      - wandb==0.20.1
      - seaborn==0.13.2
      - gpustat==0.6.0
      - black==24.3.0
      - e .
