[workspace]
authors = ["Yiming Qin, Manuel Madeira"]
channels = ["conda-forge","nvidia", "pytorch"]
name = "DeFoG"
platforms = ["linux-64"]
version = "1.0.1"

[tasks]

[system-requirements]
cuda = "12.1"

[dependencies]
python = ">=3.10, <3.12"
rdkit = "*"
graph-tool = "==2.97"
pytorch-gpu = "==2.4.0"
psi4 = "==1.9.1"

[pypi-dependencies]
ipykernel = "==6.29.5"
hydra-core = "==1.3.2"
imageio = "==2.31.1"
matplotlib = ">=3.7.1"
networkx = ">=2.8.7"
numpy = ">=1.23"
omegaconf = "==2.3.0"
overrides = "==7.3.1"
pandas = ">=1.4"
PyGSP = "==0.5.1"
pytorch_lightning = ">=2.0.4"
scipy = ">=1.11.0"
setuptools = "==68.0.0"
torch_geometric = "==2.3.1"
torchmetrics = "==0.11.4"
tqdm = "==4.65.0"
wandb = "*"
seaborn = "==0.13.2"
gpustat = "==0.6.0"
black = "==24.3.0"
defog = {path=".", editable = true}